### PR TITLE
migrate to Honey SQL 2 and create bash to build #9

### PR DESCRIPTION
**Pull request by RonildoSS**

### CODE REVIEW

**Comment by urba1n** [comment]
I notice following error in the log. But I am not sure if it is releated to the driver :
``
2023-04-20 15:53:01,922 WARN sync.util :: Error running step 'sync-timezone' for dremio Database 19 'DM product' clojure.lang.ExceptionInfo: Error querying database "DM product" for current time: Error executing query: FUNCTION ERROR: Failure parsing the formatting string at column 23 of: YYYY-MM-DD HH24:MI:SS.MS TZ
``

**Comment by Baoqi** [comment]
Thanks a lot, @RonildoSS .    Since I also need to change the github actions related with build script, I mainly picked up several of your changes,   but without merge this PR directly, sorry about that. 

Close this PR for now, Thanks.

**Comment by RonildoSS** [comment]
> Thanks a lot, @RonildoSS . Since I also need to change the github actions related with build script, I mainly picked up several of your changes, but without merge this PR directly, sorry about that.
> 
> Close this PR for now, Thanks.

No problem, happy to help

**Comment by RonildoSS** [comment]
@Baoqi 
No problem, happy to help

**Pull request closed without merging**
